#!/bin/bash
# xsel | festival --tts

# init conda for this script
source /etc/profile.d/conda.sh

# must activate the pb env before running piper which is installed in the pb env
conda activate pb 

##  substitute punctuation with semicolons
input=$(xsel)
output="${input//\!/\;}"
output="${output//\?/\;}"
output="${output//\./\;}"

echo "$output"

echo "$output" | piper \
  --model en_US-lessac-medium \
  --output_file - | ffplay -nodisp -autoexit -loglevel quiet -i -
