# Set to true to use lowercase keywords instead of uppercase.
lowercaseKeywords: false
connections:
  - alias: pg
    driver: postgresql
    dataSourceName: postgresql://root:secret@127.0.0.1:6432/betterproblems



