require('plugins')
require('treesitter-config')
require('nvim-tree-config')
require('which-keys')
require('basic-config')
require('keykinds')
require('cmp-config')
require('theme')
require('lsp')
require('lualine-config')
require('buffer-line-config')
require('telescope-config')
require('go').setup()
require('nvim-autopairs').setup {}
require('nightfox')
